"""add reference_videos and generated_videos tables

Revision ID: 14a0b1d17c9e
Revises: cb8f5b405a07
Create Date: 2026-03-20 22:27:38.117101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a0b1d17c9e'
down_revision: Union[str, Sequence[str], None] = 'cb8f5b405a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
